Rick\AppBundle\Entity\Admin:
    type: entity
    table: admins
    repositoryClass: Rick\AppBundle\Entity\AdminRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        adminname:
            type: string
            length: 255
        name:
            type: string
            length: 255
        password:
            type: string
            length: '100'
        email:
            type: string
            length: '100'
        salt:
            type: string
            length: '100'
    lifecycleCallbacks: {  }
