Rick\AppBundle\Entity\User:
    type: entity
    table: users
    repositoryClass: Rick\AppBundle\Entity\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        username:
            type: string
            length: 255
        name:
            type: string
            length: 255
        password:
            type: string
            length: '60'
        email:
            type: string
            length: '100'
    lifecycleCallbacks: {  }
